### ISSUE TITLE
Add option to not show type on hover

### ISSUE THREAD

**Issue by XVincentX** [mohsen1/json-formatter-js#1]
Hey,
at first, thank you for your work.

I was wondering whether would be possible to add an option that could avoid show the type of complex objects:

![image](https://cloud.githubusercontent.com/assets/1416224/10367244/97354d8a-6dcf-11e5-8943-eb8ec2a3ef23.png)

In this case, would be great if I could hide the `Object` and `Array` indication.
Thanks!

**Comment by mohsen1** [comment]
Have you checked out hoverPreview options? https://github.com/mohsen1/json-formatter-js#hover-preview

**Comment by XVincentX** [comment]
I tried it, but I can still see the type.

![image](https://cloud.githubusercontent.com/assets/1416224/10885287/d9e54ff2-817c-11e5-8217-c16889dd169d.png)

See `Object` and `Array [2]`

**Comment by mohsen1** [comment]
Those are not shown on hover. they are always there. I have this [issues](https://github.com/mohsen1/json-formatter-js/issues/4) open for generating valid JSON. But even with that plan is to show `Object` and other constructor names without making them copy-able.
