### ISSUE TITLE
hyperlinks as json attribute values

### ISSUE THREAD

**Issue by maruthi1255** [mohsen1/json-formatter-js#10]
HI ,
How can we parse the hyperlinks if any attribute has it.
Example : `{"links" : "some text <a href="https://github.com">GitHub</a>"}`
How can we show it in json displaying the only link as  below.
``` 
{

  "links" : "some text GitHub"
}
```

And on click on GitHub, it has to redirect to GitHub URL.

Please let me know how can we achieve this using this library.

**Comment by mohsen1** [comment]
This module does not render strings as HTML. It's not designed to do that. You can fork it and make it render strings as HTML. You will need to take HTML string safety in consideration, otherwise this can open up XSS security volubility.
