### ISSUE TITLE
Convert numbers to string - Large numbers get rounded

### ISSUE THREAD

**Issue by Rykus0** [mohsen1/json-formatter-js#128]
createTextNode is rounding long integers.  We can avoid this by converting numbers to string first.
This was in Chrome on MacOS.  Confirmed on FireFox Dev on windows as well.

![image](https://github.com/mohsen1/json-formatter-js/assets/1745718/c46dee19-c366-452e-a780-80982497f1c7)

**Comment by Rykus0** [comment]
This is actually a limitation on integer precision.  Not much to be done about it but convert it to a string before it even gets this far.

**Comment by mohsen1** [comment]
I'd merge a pull request for this. 

A side note: if your JSON that you start with has really big integers, `JSON.parse` will fail to parse. You probably want a custom parser that parses into `bigint`
https://github.com/sidorares/json-bigint
