### ISSUE TITLE
Control order of displayed attributes

### ISSUE THREAD

**Issue by PaulBernier** [mohsen1/json-formatter-js#15]
Hey,

It'd be very nice to be able to control the order the attributes are displayed. I know ES doesn't specify order of attributes when iterating them. But still here it'd be very useful to display attributes by alphabetic order for instance so the display remain consistent.

Thank you!

**Comment by mohsen1** [comment]
I think it would be out of scope of this module to specify sorting of the keys. In most JS runtimes something like this should work:

```js
const obj = {x: 1, a: 2}
const sortedKeysObj = Object.keys(obj).sort(/* any comparer you like */).reduce((key, sorted)=> 
  Object.assign(sorted, {[key]: obj[key]})
, {});
// pass sortedKeysObj to JSONFormatter now...
```

**Comment by PaulBernier** [comment]
I actually don't think it's out of the scope of your module, to me it sounds like a legit feature to have a bit more control on how things are displayed. I expect a display module to allow me to display things in a consistent way :)

Thanks for providing a workaround though!

**Comment by mohsen1** [comment]
I'm closing this since I have no plan to implement the requested feature.
