### ISSUE TITLE
Won't display multiple keys with the same name

### ISSUE THREAD

**Issue by maryjos** [mohsen1/json-formatter-js#18]
Ran into this issue when trying to display an update JSON object for Solr which uses multiple keys with the same name... something that is allowed in a JSON object, but apparently the formatter can't handle this kind of structure and only displays the last one.

**Comment by mohsen1** [comment]
It's impossible to know if a JSON string has repeated keys without rewriting the JSON parser. It's generally an error in you JSON if you have repeated keys.

**Comment by maryjos** [comment]
Again, this is actually how the JSON is *required* to be built for the API I am working with. Repeated keys are not excluded by the JSON spec, just discouraged. It's certainly led to some heated discussions about the spec having been written that way (see https://esdiscuss.org/topic/json-duplicate-keys) but there definitely are APIs that use repeated keys in them, and Solr search is one of them. I can understand if you don't want to fix this, but it's NOT an error in JSON to have them.

**Comment by mohsen1** [comment]
In JavaScript you can't parse a JSON object string into an object structure to begin with.
