### ISSUE TITLE
Option to escape html in the rendered JSON

### ISSUE THREAD

**Issue by PaulBernier** [mohsen1/json-formatter-js#20]
Hey,
Is there a way to escape html contained in the JSON? Because if the JSON contains some values with injected html then it is rendered. Which is mostly likely not the behaviour you want (so I assume it should not be an option but the default behaviour).
Thanks.

**Comment by mohsen1** [comment]
This shouldn't be an issue anymore. 

1. Are you sure you are using the latest?
2. Do you have an example JSON to reproduce it?

**Comment by PaulBernier** [comment]
Ok I was not sure if it was implemented or not. I updated my file with the latest bundle.js and it fixed it. Perfect thank you!
