### ISSUE TITLE
Use master as  gh-page

### ISSUE THREAD

**Issue by juanjoDiaz** [mohsen1/json-formatter-js#29]
Hi,

Yesterday I fixed a bug on the gh-pages branch been out of sync. This will happen every time you update the master branch and forget to merge to gh-pages.

Since for this project, the gh-pages branch is the same as master you can simply get rid of it and configure the repo so the master branch is serving the github pages. You can do that on the settings tab.

**Comment by mohsen1** [comment]
Thanks for the note. Just did it.
