### ISSUE TITLE
Possibility to show curlt parentheses

### ISSUE THREAD

**Issue by RomanGotsiy** [mohsen1/json-formatter-js#3]
Your another project [json-schema-view-js](https://github.com/mohsen1/json-schema-view) displays curly parentheses. It would be great to have possibility to show them here too (e.g. via an option)

**Comment by mohsen1** [comment]
Yes, it is something I want to do
https://github.com/mohsen1/json-formatter/issues/17

**Comment by mohsen1** [comment]
See #7
