### ISSUE TITLE
Option to sort properties

### ISSUE THREAD

**Issue by sachingsachin** [mohsen1/json-formatter-js#30]
It will be a nice option to add. Example:

current behavior:

``` json
{
  "a": 1,
  "c": 2,
  "b": {
      "z": 1,
      "y": 2
   }
}
```

With sorting option (ascending/descending flavors):

``` json
{
  "a": 1,
  "b": {
      "y": 2,
      "z": 1
   },
  "c": 2,
}
```

Note that we sort inside the nested objects too.

Why is this useful?
Sorting imposes an automatic grouping on the similar properties.
Example currently similar properties are seen as:

``` JSON
{
  "ui.filter.params":null,
  "storm.messaging.netty.client_worker_threads":1,
  "ui.actions.enabled":true,
  "storm.cluster.mode":"distributed",
  "zmq.linger.millis":5000,
  "supervisor.enable":true
}
```

This is very inconvenient and a sort option will really make it easy to read.

**Comment by mohsen1** [comment]
See https://github.com/mohsen1/json-formatter-js/issues/5 and https://github.com/mohsen1/json-formatter/issues/30

**Comment by sachingsachin** [comment]
Yes, clients can do it themselves no doubt, but an option in the library would be more convenient especially for sorting nested objects, otherwise all the sorting-clients have to write the same piece of code again and again.

**Comment by mohsen1** [comment]
Alright, this is coming up again and again. I don't have time to do it but will accept a pull request. Sorting should be:
 

- Optional
- Uses `Array.prototype.sort` by default but allows overriding it via configuration 
- Does not sort arrays! 
- Does it deeply
