### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by lukeramsden** [mohsen1/json-formatter-js#41]
TravisCI build currently fails

**Comment by mohsen1** [comment]
A pull request is welcome. I'm not sure why it's failing

**Comment by lukeramsden** [comment]
@mohsen1 it's because there are no tests, which means it says 0 tests pass, which is counted as an error

**Comment by mohsen1** [comment]
There are tests. Try running on your machine

**Comment by mohsen1** [comment]
this is test

**Comment by mohsen1** [comment]
### Impact of this change on bundle sizes:
| File | Before | After | Change |
| ---- | ------ | ----- | ------ |
|      |        |       |        |
