### ISSUE TITLE
demo site is broken

### ISSUE THREAD

**Issue by garfieldnate** [mohsen1/json-formatter-js#46]
I tried looking at the demo site with both Chrome and Firefox, but the formatted/collapsible JSON is not displayed. It looks like maybe a pre-processor wasn't run on the JS? Here are the console errors:

    json-formatter.js:1 Uncaught ReferenceError: module is not defined
        at json-formatter.js:1
    azimi.me/:147 Uncaught ReferenceError: JSONFormatter is not defined
        at http://azimi.me/json-formatter-js/:147:29
        at Array.forEach (native)
        at http://azimi.me/json-formatter-js/:145:16

**Comment by mohsen1** [comment]
Fixed in 2.1

**Comment by marketarea** [comment]
json-formatter.js:1 Uncaught ReferenceError: module is not defined
    at json-formatter.js:1
(anonymous) @ json-formatter.js:1
(index):21 Uncaught SyntaxError: Unexpected identifier
