### ISSUE TITLE
Missing styles

### ISSUE THREAD

**Issue by sstchur** [mohsen1/json-formatter-js#48]
I have an Aurelia-based app, using Typescript and webpack.  The control is working for me, but it seems to be missing styling and I'm unsure why?

I'm importing as:

import JSONFormatter from 'json-formatter-js'

And I'm using the control as:

let jsonFormatter = new JSONFormatter(myData);
someElement.appendChild(jsonFormatter.render());

It renders, and I see everything correctly, and I can click elements and expand them, but I see no styling, no icons, no indention.  

How can I ensure the styles get loaded properly so it looks like your demo?  Or is there an issue with Aurealia/webpack and this control?

**Comment by mohsen1** [comment]
Styles are  added to JS using the style loader. See the demo, it's not importing css or doesn't have a css loader in webpack

**Comment by sstchur** [comment]
It works if you clone your demo repo, but if you npm install it into an existing project, it doesn't work.  If I examine /dist/json-formatter.js, it is only 245 lines, and the styles are not embedded.  I can see that they are embedded in the one where I clone the repro from your github.  Not sure what the difference is, but I can even run webpack directly against the version that was npm installed into my project's node_modules directory.  It generates dist/json-formatter.js, but again, the styles aren't embedded.

**Comment by mohsen1** [comment]
Maybe I've not published the changes. With #47 I need to publish a new version anyways. Will publish soon

**Comment by mohsen1** [comment]
can you try 2.2?

https://github.com/mohsen1/json-formatter-js/releases/tag/v2.2.0

**Comment by sstchur** [comment]
Yes, that did it!  Thanks much. It's working great now.
