### ISSUE TITLE
Possible to implement in a Wordpress plugin ?

### ISSUE THREAD

**Issue by gordielachance** [mohsen1/json-formatter-js#59]
Hi, sorry to ask that dumb thing, but I don't know anything at AngularJS.
Is it possible to embed your formatter in a Wordpress plugin ?  I mean, all I would need would be a javascript file but I don't see one here...
THanks !

**Comment by mohsen1** [comment]
This lib doesn't have any dependencies. It should work in any environment.

**Comment by gordielachance** [comment]
Thanks, but where is located that file in your repo ? :)

**Comment by mohsen1** [comment]
It's not check into the repo. In your terminal `npm install json-fromatter-js` and then navigate to `node_modules/json-formatter-js/dist`. There you can find the files
