### ISSUE TITLE
toJSON 

### ISSUE THREAD

**Issue by itismynamenow** [mohsen1/json-formatter-js#61]
Thk for great lib. I found one issue. Example: 
if following used:
```
            formatter = new JSONFormatter(window);
            output.appendChild(formatter.render());
```
then window.performance will be empty while in console usually it contains plenty of properties.
This happens because window.performance has .toJSON() that returns an object which is treated as a value on lines 355-357.
```
// Append value content to value element
      const valuePreview = getValuePreview(this.type, this.json, this.useToJSON ? this.json.toJSON() : this.json);
      value.appendChild(document.createTextNode(valuePreview));
```
as result things are represented incorrectly. I guess if object has toJSON is should be treated as object and not as value. Though I am not very sure...

**Comment by mohsen1** [comment]
Use can configure this behavior with `useToJSON` option. no?

**Comment by itismynamenow** [comment]
The issue is solved with useToJSON=false. I wrote the previous comment to point that something is wrong with a result of toJSON() treated as value instead of object which in my opinion leads to bugs in case if someone decides to set useToJSON=true. Thank you for the response.
