### ISSUE TITLE
Rendering object of type File

### ISSUE THREAD

**Issue by RobinPel** [mohsen1/json-formatter-js#62]
When using this library to display an object of type File, an empty element is rendered. The reason for this is documented [here](https://stackoverflow.com/a/29281243).

Is is currently possible to support objects of type File and if not, would it be possible to implement in this library?

A full working example is available on https://stackblitz.com/edit/json-formatter-js-file.

**Comment by mohsen1** [comment]
I much rather not to have such modifiers in core of this library. `File` is just one of many classes that implement their own `toJSON` method. You can convert your JSON before passing it to this library instead.
