### ISSUE TITLE
Dist folder missing...?

### ISSUE THREAD

**Issue by plindelauf** [mohsen1/json-formatter-js#63]
I'm looking to use this plugin purely in a browser and I was hoping to find the native JS code in a `dist` folder (as mentioned in the documentation). However, there is no `dist` folder. Can you help?

**Comment by mohsen1** [comment]
Are you sure? Unpkg is able to find it:

https://unpkg.com/json-formatter-js@2.2.0/dist/json-formatter.js

**Comment by plindelauf** [comment]
Thanks. I was looking in the master branch here on GH.
