### ISSUE TITLE
Please do not publish backwards incompatible versions with only patch update

### ISSUE THREAD

**Issue by mitar** [mohsen1/json-formatter-js#67]
You made a patch update from 2.2.0 to 2.2.1 where you removed `dist` and added `src` to npm ignore. This now breaks the build on older NPM versions which do not build files automatically.

Patch versions should not be misused like this. This is not even a backward compatible change so you should change major version.

Can you please provide 2.2.2 version where you keep src and dist, and then if you want publish a new version 2.3.0 or even 3.0.0?

**Comment by mohsen1** [comment]
Curious how you were using src? It's all TypeScript.

**Comment by mohsen1** [comment]
Sorry about this. I can't unpublish it anymore. Moving forward I will be more thoughtful. Lock files are making this kind of issue happening less.

**Comment by mitar** [comment]
Lock files are not used for package dependencies. So if I publish a package depending on this package, a new person installing my package gets a broken dependency (this package). That person does not yet have a working lock file for their app.

**Comment by mitar** [comment]
But yes, it happens. :-) This is life of a developer. So no worries, no hard feelings here. I have also made and will probably made similar mistakes as well. Dependencies are hard.
