### ISSUE TITLE
How to use as a standalone script?

### ISSUE THREAD

**Issue by bendavis78** [mohsen1/json-formatter-js#71]
For those of us that don't typically use javascript build tools, is there a place to find a standalone script that can just be dropped into a <script> tag?

**Comment by mohsen1** [comment]
this requires users to use Webpack or similar tools. You can probably make it emit UMD too

 https://github.com/mohsen1/json-formatter-js/blob/1f561d2efee44238ace56c1ba6db2d2cb915311b/webpack.config.js#L16

**Comment by Juniuz** [comment]
Hi, I was wondering could you guys provide an example on how to configure json-formatter-js using gulp and babel (transpile from ES6 to ES5) kind of?

**Comment by mohsen1** [comment]
Webpack can compile to UMD too. if a PR comes in with that fix I'll merge it! :)

**Comment by will-r-chase** [comment]
Hi, I don't know the first thing about Webpack or other build tools, but I would really love to use this as a standalone via CDN. From a little googling it seems possible if you just change `libraryTarget` in the webpack.config.js to `'umd'`. 

Is that really all that's needed? That seems way too simple, but if that will really work I can submit a PR.

**Comment by mohsen1** [comment]
Yeah it's that simple! I might do it but I'm pretty busy right now.

**Comment by campbeln** [comment]
Can someone please provide the UMD version of this script? Or at least the steps to build it via webpack?

I find it a bit misleading that this is referred to as Vanilla Javascript and yet required WebPack to work so a UMD version provided in Github and/or linked to would be greatly appreciated.
