### ISSUE TITLE
Array with "string" item render error

### ISSUE THREAD

**Issue by ovcharik** [mohsen1/json-formatter-js#72]
Can't render array with `"string"` item.

```
TypeError: str.replace is not a function
    at escapeString
    at getValuePreview
    at getPreview
    at Array.map (<anonymous>)
    at JSONFormatter.getInlinepreview
    at JSONFormatter.render
```

Minimal JSON that not will be rendered:

```json
["string"]
```

Also an error happen for the following JSON:

```json
{
  "tags": ["string", "number"]
}
```

**Comment by juanjoDiaz** [comment]
I couldn't reproduce it with any of the two examples that you give.
![image](https://user-images.githubusercontent.com/3322485/69901311-705f5f80-1388-11ea-90fb-754c5df75794.png)

![image](https://user-images.githubusercontent.com/3322485/69901325-94bb3c00-1388-11ea-9245-d495272d8b29.png)

**Comment by ovcharik** [comment]
It turns out that doesn't work with only with `hoverPreviewEnabled` flag.

<img width="434" alt="Annotation 2019-11-30 233949" src="https://user-images.githubusercontent.com/4432904/69905849-ec7a9700-13ca-11ea-8646-72810367d0f6.png">
