### ISSUE TITLE
Option to not link URL-looking values

### ISSUE THREAD

**Issue by john-kurkowski** [mohsen1/json-formatter-js#73]
I have JSON with invalid or potentially unsafe URLs I _don't_ want users to click. What do you think about an option to turn off this library's `a[href]` elements? Or perhaps a hook into node creation?

**Comment by john-kurkowski** [comment]
To work around this, I can use `MutationObserver` to manually convert `a`s to `span`s. Seems like brittle, private API though.

**Comment by mohsen1** [comment]
I think this use case is out of scope of this project. It's open source, so feel free to fork and add that custom behavior! ❤️
