### ISSUE TITLE
Custom name for objects

### ISSUE THREAD

**Issue by fr0** [mohsen1/json-formatter-js#74]
Thanks for the library - it's very useful.

All of my objects come from `JSON.parse`, which means they aren't classes. The end up getting printed as `Object` based on this code:  https://github.com/mohsen1/json-formatter-js/blob/master/src/helpers.ts#L29

However, many of them have a `type` property. What I'd really like is to use the value of the `type` property as the object name, and hide the `type` property.

I think the best way to handle this would be to allow developers to provide a `config.nameOverride` function that would be called for each object if it is present, and if it returns a value, use that value instead. I'd be happy to implement this if you are willing to accept the pull request.

**Comment by mohsen1** [comment]
I think this is out of scope. Unless others require similar functionality I would like to keep this library small. It's OSS, so you get to use your own fork. Thanks for your contribution! ❣️

**Comment by radwaElyamany** [comment]
@mohsen1 can we add this functionality please?
