### ISSUE TITLE
Is this module maintained?

### ISSUE THREAD

**Issue by juanjoDiaz** [mohsen1/json-formatter-js#80]
Hei @mohsen1 ,

I've noticed that some of the issues in this module have been sitting here for a long time even though they were pretty trivial to fix. Also, my PRs seem to be just sitting there (one has been there for a month and a half).

So I was wondering if you are currently maintaining this module?
If you don't have time for this, I'd be happy to help to maintain it.

**Comment by mohsen1** [comment]
Hi, yes I'm trying to allocate some time accepting PRs and looking into issues. I don't maintain it actively. 

I've merged your PR and will release it soon.
