### ISSUE TITLE
AngularJS/Question - Pass-in Config into directive/Preview without Hovering

### ISSUE THREAD

**Issue by dinbtechit** [mohsen1/json-formatter-js#81]
Great work! hats off!.

Unfortunately I couldn't get the `Config` setting to work. I tried as specified in the Documentation -> https://github.com/mohsen1/json-formatter-js#config-object. 
Not sure if I am missing something.

**Also have following questions:**

1. How do I pass-in the `config` in the angular `directive`?
2. Is there a way to display preview without hovering?
3. Hide the `object` tag and display only the json data.
    ![image](https://user-images.githubusercontent.com/17984781/70913488-7f7f1800-1fec-11ea-8736-2eafd489da4b.png)

Here is my sample code: 

**app.js** (using AngularJS 1.7.X)

``` javascript
var app = angular.module('myApp', ['jsonFormatter']);
app.controller("myCtrl", function($scope)) {
  $scope.myJson = {
   hello : 'world'
   }

  /* ⚠️ THIS CONFIGURATION IS NOT WORKING */
  $scope.config = {
    hoverPreviewEnabled: true,
    hoverPreviewArrayCount: 200,
    hoverPreviewFieldCount: 10,
  }
}
```
**HTML**
``` html
<html>
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.7.8/angular.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/json-formatter/0.7.0/json-formatter.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/json-formatter/0.7.0/json-formatter.min.js">
</script>
<script src="app.js">
</script>

</head>
<body>
   <div ng-app="myApp" ng-controller="myCtrl">
       <json-formatter open="1" json="myJson" config="config"></json-formatter> 
    </div>
</body>
</html>
```

**Comment by mohsen1** [comment]
There is https://github.com/mohsen1/json-formatter which is made for Angular
