### ISSUE TITLE
Use browserify standalone build for the dist

### ISSUE THREAD

**Issue by D34THWINGS** [mohsen1/json-formatter-js#9]
Instead of exporting on your own on the window, use the browserify `standalone` option to export your bundle in CommonJS, Window and AMD at the same time. This will also ensure that people using your library in Browserify environment will not have conflicts with `require` statements into your build as they will be replaced

Thanks for your work

**Comment by jaredcnance** [comment]
+1

**Comment by D34THWINGS** [comment]
@mohsen1 Will you do it or should I do the PR ?

**Comment by D34THWINGS** [comment]
I think this issue needs an update since build is no longer done with browserify but still, there's a `require` call remaining in the dist that fails when using from browserify

**Comment by mohsen1** [comment]
I was in middle of converting this to webpack+typescript. I forgot where I left the work at. I'll take a look tonight.

**Comment by mohsen1** [comment]
If you're still having the original problem it's probably because you haven't upgraded the dependency version of this module. I recently [released a major version](https://github.com/mohsen1/json-formatter-js/releases/tag/v1.0.0) after refactoring this with TypeScript and Webpack. [You can see here](https://github.com/mohsen1/json-formatter-js/blob/master/dist/bundle.js#L1-L10) that it does proper UMD exports. 

Please let me know if you're still having this issue after upgrading.

**Comment by andyburke** [comment]
Hi, I think I am still seeing an issue with this in v1.3.0:

```
> browserify src/main.js -t [ envify --NODE_ENV ${NODE_ENV}  ] -o www/js/bundle.js

Error: Cannot find module '!!./../node_modules/css-loader/index.js?sourceMap!./../node_modules/less-loader/index.js?sourceMap!./style.less' from '/home/XXX/node_modules/json-formatter-js/dist'
```

**Comment by mohsen1** [comment]
@andyburke are you sure? Please try building from master. Maybe release is not good.

**Comment by andyburke** [comment]
@mohsen1 same thing with master

**Comment by andyburke** [comment]
I think it could be this line:

https://github.com/mohsen1/json-formatter-js/blob/master/dist/json-formatter.js#L511

I'm not sure that browserify cares about if blocks when trying to understand what it needs to include

**Comment by mohsen1** [comment]
You can depend on source and let browserify compile for you. I think webpack and browserify are conflicting here

**Comment by andyburke** [comment]
I mean, I would like to, but it seems like that's not possible given how you've got the module set up. It feels like you should just compile from TypeScript to js and not involve webpack in producing your dist file, then leave it up to the consumer to choose browserify or webpack.
