### ISSUE TITLE
Open hyperlinks in separate tab?

### ISSUE THREAD

**Issue by alvaro1728** [mohsen1/json-formatter-js#94]
Is there a way to add `target="_blank"` to hyperlinks?

Thanks,
Alvaro

**Comment by mohsen1** [comment]
No, but I will accept a PR that adds an optional method to the configuration for determining if a link should be opened in a new tab or not:

```ts
import JSONFormatter from 'json-formatter-js'

const myJSON = {external_link: 'http://example.com',  internal_link: 'https://my-domain.com' };

const formatter = new JSONFormatter(myJSON, 1, {
  getTargetForHyperlink(link: string) {
   const url = new URL(link);
   return url.hostname === 'my-domain.com' ? '_self' : '_blank';
  }
});

document.body.appendChild(formatter.render());

```

**Comment by mohsen1** [comment]
This can be addressed with https://github.com/mohsen1/json-formatter-js/issues/17 which is a TODO in this repo
