### ISSUE TITLE
Dark theme background is white

### ISSUE THREAD

**Issue by Nekzuris** [mohsen1/json-formatter-js#96]
The background of the dark theme is white, I think something is missing in the css.

**Comment by mohsen1** [comment]
I'm seeing this 4 years later. hopefully your issue is not still happening. Closing this issue for now

**Comment by Nekzuris** [comment]
No, it didn't fix itself after 4 years.

And your live demo isn't working either.

**Comment by Nekzuris** [comment]
I see you've fixed it, thanks.

But for the dark theme example, you had to manually set a dark background.
Shouldn't that be in the main CSS and automatically set when selecting the dark theme?

**Comment by mohsen1** [comment]
I'm not setting a background in "light mode" either. I'm assuming in the dark mode, the background is dark. I don't want to dictate what shade of gray is preferred for this lib.

**Comment by Nekzuris** [comment]
I've never seen a dark mode implemented like that before.
